### ISSUE TITLE
App crashes on new Aluminum Ice X64 bit distro 

### ISSUE THREAD

**Issue by pyrophreak** [NoxiousKarn/Showerthoughts#1]
When i added the repository and updated the database i got a string of errors when running pwnagotchi plugins update it broke the list functionality of the plugin command and gave the following error message.

Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 125, in <module>
    rc = plugins_cmd.handle_cmd(args, config)
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/cmd.py", line 85, in handle_cmd
    return list_plugins(args, config)
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/cmd.py", line 239, in list_plugins
    print(line.format(name=plugin, width=max_len, version='.'.join(available_version), enabled='-', status='available'))
TypeError: can only join an iterable.

Any help or suggestions appreciated.

**Comment by NoxiousKarn** [comment]
showerthoughts is not a plugin and does not affect the plugins/cmd.py file in anyway. Showerthoughts is a modification to Voice.py to get it not to read boring text but instead grep and produce a prewritten headline from an RSS feed...

there is likely a clue to what is happening in that file if you check those lines what do they reference line 85 and line 239.


one thing you can try is to uninstall following the instructions to remove old RSS feed data and then reinstall.

**Comment by pyrophreak** [comment]
> showerthoughts is not a plugin and does not affect the plugins/cmd.py file in anyway. Showerthoughts is a modification to Voice.py to get it not to read boring text but instead grep and produce a prewritten headline from an RSS feed...
> 
> there is likely a clue to what is happening in that file if you check those lines what do they reference line 85 and line 239.
> 
> one thing you can try is to uninstall following the instructions to remove old RSS feed data and then reinstall.

The line references return list_plugins(args, config)

**Comment by NoxiousKarn** [comment]
Yep not related as it is not a plugin and does not use the plugin system
