### ISSUE TITLE
Cronos job is deleting my showerthoughts

### ISSUE THREAD

**Issue by vollukas** [NoxiousKarn/Showerthoughts#3]
Along with support for python 3.9 and 3.11 is another issue (I think)

Seems like after running cronos job, my files with showerthoughts are deleted and empty string is displayed instead.
I set it to run every 5 min and seems like replacing /python3 path with just "python" instead fixed it
![image](https://github.com/NoxiousKarn/Showerthoughts/assets/24632372/b17d0e4e-08eb-4eb7-b033-3c84bc335ebe)

Thanks again for this plugin, I might try reuse it on something different than pwnagotchi since I love random thoughts so much :D

**Comment by vollukas** [comment]
I was also thinking if 1/3 or 50/50 is better and came to the conclusion that I want more showerthoughts while also preserving text variety :D 
![image](https://github.com/NoxiousKarn/Showerthoughts/assets/24632372/261ad747-9131-4e72-bb5f-678a59ac0e48)

**Comment by NoxiousKarn** [comment]
good call on the cronjob gonna modify the instructions and scripts now THANKS!
